# Generated by Django 4.1.7 on 2023-03-26 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sustainabilityapp', '0002_remove_profile_id_profile_daily_progress_and_more'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='profile',
        #     name='id',
        # ),
    ]
