# Generated by Django 4.1.7 on 2023-03-26 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sustainabilityapp', '0002_remove_profile_id_profile_daily_progress_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Challenges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(max_length=1000)),
                ('ch1', models.CharField(max_length=1000)),
                ('ch2', models.CharField(max_length=1000)),
                ('ch3', models.CharField(max_length=1000)),
                ('ch4', models.CharField(max_length=1000)),
                ('ch5', models.CharField(max_length=1000)),
                ('ch6', models.CharField(max_length=1000)),
            ],
        ),
        # migrations.RemoveField(
        #     model_name='profile',
        #     name='id',
        # ),
    ]
