# Generated by Django 4.1.7 on 2023-03-26 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sustainabilityapp', '0003_challenges_remove_profile_id'),
        ('sustainabilityapp', '0003_remove_profile_id'),
    ]

    operations = [
    ]
